### ISSUE TITLE
legal ip dscp values

### ISSUE THREAD

**Issue by chunhui-pang** [floodlight/loxigen#423]
It seems the ip dscp implementation between loxigen and ovs aren't consistent. Loxigen generate java files which use 0-63 as ip dscp values. But ovs thinks ip dscp values must be times of 4, i.e., [0, 63] * 4 (because the last two bit of ip dscp field is reserved). When I set the ip tos field with 22, and try to install the flow rule, ovs reject the rule install request, saying there is illegal parameters.

**Comment by andi-bigswitch** [comment]
@chunhui-pang - looking at the spec, it looks to me like loxigen complies with the spec, and OVS may not.

From the OpenFlow spec, version 1.4, page 149:
> * Format: 8-bit integer with 2 `most-significant` bits forced to 0.
> * Only the lower 6 bits have meaning.

To me, that means that TOS '22' *should* be represented as `22` (binary `00010110`), not 22 * 4 (binary `01011000`).

**Comment by andi-bigswitch** [comment]
@chunhui-pang from the OF spec it seems to me that loxigen's behavior is currently spec-compliant, and OVS's behavior may be not. Thus closing this issue. Let me know if you think I am mis-interpreting the spec.
