### ISSUE TITLE
OFBundleAddMsg Builder not using same xid as the nested message

### ISSUE THREAD

**Issue by AndreMantas** [floodlight/loxigen#454]
Hi. I found a possible bug regarding the way OFBundleAddMsg's are built.

As mentioned in the OF 1.4 spec:

**7.3.9.6 Adding messages to a bundle**
Message added in a bundle should have a unique xid to help matching errors to messages, **and the xid of the bundle add message must be the same**. A switch may optionally verify that the two xid of a message are consistent or that two messages of the bundle don’t have the same xid, and if this is the case refuse to add the new message to the bundle and send an ofp_error_msg with OFPET_BUNDLE_FAILED type and OFPBFC_MSG_BAD_XID code.

After some testing, looks like loxigen uses a new xid for each message (the BundleAdd message and the nested message). When using this code:

`OFMessage msg = ...`
`OFBundleAddMsg add = sw.getOFFactory().buildBundleAddMsg() .setBundleId(BundleId.of(id)).setFlags(flags).setData(msg).build();`

The switch replies with the above error mentioned in the spec (BAD_XID).

Simply adding `.setXid(msg.getXid())` to the builder fixed the problem. The other messages (open request, close request and commit request seem to be working so far).

**Comment by andi-bigswitch** [comment]
@AndreMantas - fix merged (#473).
