### ISSUE TITLE
Adding an OpenFlow Experimenter Extension to Loxigen -Java

### ISSUE THREAD

**Issue by EnasAhmad** [floodlight/loxigen#468]
Hello,
I followed this tutorial: https://floodlight.atlassian.net/wiki/display/floodlightcontroller/How+to+Add+an+OpenFlow+Experimenter+Extension
to add a new oxm to loxigen in java. I made the following steps:

1. I created a new file in the openflow_input folder named oxm-http, with the following content:
/* 
 * oxm-http:
 * Match on HTTP method
 */
  
#version 4
#version 5
  
struct of_oxm_http_method : of_oxm {
    uint32_t type_len == 0xffff0201;
    uint8_t value;
};

2. In the MatchFields.java file I added  HTTP_METHOD, at the end of the enumeration.

3. In the MatchField.java file I added the following method:
`   public final static MatchField<U8> HTTP_METHOD =
            new MatchField<U8>("http_method", MatchFields.HTTP_METHOD,
            new Prerequisite<IpProtocol>(MatchField.IP_PROTO, IpProtocol.TCP));`

4. Then I run sudo make package-java to generate the jar packages, and I get these errors:

[INFO] 18 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.866s
[INFO] Finished at: Mon Mar 07 11:59:03 AST 2016
[INFO] Final Memory: 27M/1419M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project openflowj: Compilation failure: Compilation failure:
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/oxm/OFOxmHttpMethod.java:[28,58] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/oxm/OFOxmHttpMethod.java:[41,52] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/oxm/OFOxmHttpMethod.java:[31,16] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/oxm/OFOxmHttpMethod.java:[33,11] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/oxm/OFOxmHttpMethod.java:[46,20] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/oxm/OFOxmHttpMethod.java:[48,15] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/ver13/OFOxmHttpMethodVer13.java:[66,23] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/ver13/OFOxmHttpMethodVer13.java:[75,18] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/ver13/OFOxmHttpMethodVer13.java:[124,23] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/ver13/OFOxmHttpMethodVer13.java:[134,18] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/ver13/OFOxmHttpMethodVer13.java:[184,23] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/ver13/OFOxmHttpMethodVer13.java:[194,18] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/ver14/OFOxmHttpMethodVer14.java:[66,23] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/ver14/OFOxmHttpMethodVer14.java:[75,18] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/ver14/OFOxmHttpMethodVer14.java:[124,23] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/ver14/OFOxmHttpMethodVer14.java:[134,18] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/ver14/OFOxmHttpMethodVer14.java:[184,23] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] /home/enas/loxigen/loxi_output/openflowj/gen-src/main/java/org/projectfloodlight/openflow/protocol/ver14/OFOxmHttpMethodVer14.java:[194,18] unexpected type
[ERROR] required: reference
[ERROR] found: short
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
make: *** [package-java] Error 1

It seems that when the "OFOxmHttpMethod" classes are generated, the uint8_t type is not converted to U8 but rather to a short int. If I replace the uint8_t in oxm-http with of_mac_addr_t type just for testing it compiles successfully.
I have the latest master branch of the loxigen library, and I am building it on Ubuntu 14.04 LTS, 64-bits. and the following maven version:
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_95, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-51-generic", arch: "amd64", family: "unix"

I posted the issue on the floodlight developers group: https://groups.google.com/a/openflowhub.org/forum/#!searchin/floodlight-dev/oxm/floodlight-dev/QfdrYLmkL8k/gSk8OXHgIAAJ
and @rizard recommended that i post here.
Any idea ?
Enas

**Comment by EnasAhmad** [comment]
I repeated this on OS X 10.9.5 and it gave the same error! I think I must be missing something, any help in adding an experimenter field to loxigen would be much appreciated!

**Comment by rizard** [comment]
Just noticed your MatchField is missing the the U8 type (i.e.
MatchField<U8>) in MatchField.java.

Ryan Izard
PhD Candidate, Research/Teaching Assistant
ECE Department, Clemson University
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by EnasAhmad** [comment]
Thanks Ryan for the reply,
No it seems for some reason when I posted the method here the MatchField<U8> got deleted and I didn't notice! I edited the post with code formatting, 

so as my original post on the floodlight developers group, this the the method I added inside MatchField.java:

`public final static MatchField<U8>  HTTP_METHOD =
                       new MatchField<U8>   ("http_method", MatchFields.HTTP_METHOD,
                       new Prerequisite<IpProtocol>(MatchField.IP_PROTO, IpProtocol.TCP));` 

I'm very sorry about the confusion!

**Comment by andi-bigswitch** [comment]
Hi @EnasAhmad, the loxigen java backend isn't very smart about auto-boxing / conversion between value types and references types.

In this case, you'll need to an explicit type declaration to the map `exceptions` in `java_type.py` to make the backend use the right reference type (U8).


Try this:
```
diff --git a/java_gen/java_type.py b/java_gen/java_type.py
index 70f6c05..d095022 100644
--- a/java_gen/java_type.py
+++ b/java_gen/java_type.py
@@ -722,6 +722,8 @@ exceptions = {
         'of_oxm_bsn_inner_vlan_vid' : { 'value' : vlan_vid_match },
         'of_oxm_bsn_inner_vlan_vid_masked' : { 'value' : vlan_vid_match, 'value_mask' : vlan_vid_match },

+        'of_oxm_http_method': { 'value' : u8obj },
+
         'of_table_stats_entry': { 'wildcards': table_stats_wildcards },
         'of_match_v1': { 'vlan_vid' : vlan_vid_match, 'vlan_pcp': vlan_pcp,
                 'eth_type': eth_type, 'ip_dscp': ip_dscp, 'ip_proto': ip_proto,
```

Let me know if this works!

**Comment by EnasAhmad** [comment]
Excellent @andi-bigswitch, works perfectly! Thank you.
and thanks @rizard for the followup, also, this would be a good addition to the floodlight tutorial.

All the best,
Enas
