### ISSUE TITLE
How to express a 16-bit port number when generating for OF1.1+?

### ISSUE THREAD

**Issue by rsharo** [floodlight/loxigen#501]
Hi folks,

I'm trying to add some Nicira-specific actions: `resubmit`, `resubmit_table`, and `exit`.

Defining the input file is pretty simple. (Nice work, all!) Here's an example for `resubmit_table`:
```
#version any

struct of_action_nicira_resubmit_table : of_action_nicira {
    uint16_t type == 65535;
    uint16_t len;
    uint32_t experimenter == 0x2320;
    uint16_t subtype == 0xe;
    of_port_no_t in_port;
    uint8_t table_id;
    pad(3);
};
```

The problem is, OpenVSwitch uses a 16-bit port number in this action even for versions of the OpenFlow protocol above 1.0.  Is there a way to force `in_port` to be marshalled as a _two byte_ field instead of _four bytes_ for OpenFlow versions 1.1+... _just for these experimenter actions_?

I know I could define the field as a `uint16_t`, but then it wouldn't be expressed as an `OFPort` in the builders and accessors.  Trying to figure out if there is a "right" way to do it.

**Comment by andi-bigswitch** [comment]
Since this is somewhat of a custom case; I would suggest making it an uint16_t in the OpenFlow input file / layer.

You can define a custom java type mapping for this in `java_type.py`; along the lines of (untested)
```python

# [under of_port]
of_port_nicira = JType("OFPort") \
         .op(read="OFPort.read2Bytes(bb)", write="$name.write2Bytes(bb)", default="OFPort.ANY")

exceptions = {
    #....
    'of_action_nicira_resubmit_table': { 'port': of_port_nicira }
}
```

**Comment by rsharo** [comment]
@andi-bigswitch Thanks much!

I'll use uint16_t for now.  Was just looking at the code you referenced... I'd want to do it for all three language bindings if I did it.  Seems a little overkill to do that just for two experimenter types.  Will revisit if it becomes a recurring problem.
