### ISSUE TITLE
Recent change to MacAddress.putTo() impacts interoperability with external systems

### ISSUE THREAD

**Issue by rsharo** [floodlight/loxigen#502]
Hi folks,

So.... I understand the desire to improve performance, but wonder if you'll consider rethinking [this commit](https://github.com/floodlight/loxigen/commit/fd6c3f530241723e43ccd5b7c56f78e1de9c0835).

Sinking those extra two bytes of zeroes may be harmless for the IPv4 header checksum algorithm, but not so for other hash algorithms. 

Example 1 - Padded hash:
```
$ echo -n $'\x00\x00\x12\x34\x56\x78\x90\xab' | md5sum -
d41d8cd98f00b204e9800998ecf8427e  -
```

Example 2 - Unpadded hash
```
$ echo -n $'\x12\x34\x56\x78\x90\xab' | md5sum -
edc3c95262a975165986e80b4247ca71  -
```

I know this isn't your problem, but some groups are doing "stuff" with Floodlight that relies on an ability to hash fields in more secure ways than traditional IPv4 checksum.  It has been nice up to now to be able to call putTo() on OFValue<T> objects without having to do a lot of instanceof and downcasting.

Can you help a brother out? :)

**Comment by andi-bigswitch** [comment]
Hi, as such I am happy to help, but I do think this comment is based on a wrong assumption. The commit in question does not "break non IP-hashes" (FWIW, we don't use IP checksum ourselves, our hash workhorse is Murmur3-128).

To expand on this: You are correct that the commit _changes_ what is being hashed. But that is not the same thing as breaking the hash (or impacting security). In particular, the new value that is hashed just adds two padding bytes; it is every bit as unique and includes every bit of entropy on the Mac Address.

I.e., while you are right that md5 (and SHA1, and murmur and every other good hash function) will compute a _different_ result from the same Mac Address after the commit, that new result has the same security and uniqueness guarantees as the result that was previously computed.

From my perspective, the contract of `PrimitiveSinkable` is not for the object to serialize itself in any particular way; nor is it guaranteed that the particular serialization is stable across version. The contract  for `PrimitiveSinkable` *is* that the object must capture all its entropy in the serialized format. 
Both the old and the new versions of putTo conform to that contract (and btw; at least with the standard Guava Hashers, neither the old nor the new version returns exactly the same value as hashing the 6 value bytes in Network Order....)

That said, while I don't buy the "breaks the hash" argumentation, I also don't think the performance benefit of that particular optimization is really anything to discuss about... 

So I am curious -- do you see an an actual failure in your application? Are you storing these Hash Values and expecting them to be unchanged across versions?

**Comment by rsharo** [comment]
@andi-bigswitch Thanks for the info!

I understand that it doesn't break Floodlight "internally" -- hashes computed with (consistent) 8-byte MAC representations will always be consistent with themselves.  Problems start when you try to interoperate with other systems that truly treat MAC addresses as 6-byte entities.

Yes, we do see an actual failure.  The hash computed by ingesting an 8-byte hash differs from the one computed with a 6-byte hash, breaking interoperability between the Floodlight-based implementation and other implementations that communicate with it.

Wonder if there is a middle ground.  If we could have a getBytes() method in the OFValueType interface, then people who needed a more exact representation of the data could get it without having to know every derived type and downcast.  The putTo() could still push optimized representations that may have padding bytes in them, but getBytes() would be expected to be slower and more accurate.

Opinions?

**Comment by rsharo** [comment]
Forgot to mention... I willing to try to write the code and submit a PR if you want to consider adding `OFValueType<T>.getBytes()` to the java binding.  I'm comfortable with Floodlight, but less-so with loxigen.

**Comment by andi-bigswitch** [comment]
So just to close the loop and make sure I understand the problem. You mention:

> Problems start when you try to interoperate with other systems that truly treat MAC addresses as 6-byte entities.

Note that Guava's hashers use  a little-endian byte-buffer; i.e., bytes gets swapped when you do `putInt` and even the old version does not computed the same hash values as hashing the 6-byte array would give you.

So, in order to interoperate with an external system you wrote a custom PrimitiveSink that uses a Big-Endian buffer? Or did you faithfully reproduce the choice of using a little-endian buffer and doing `putInt` first and `putShort` second? The first seems like a reasonable (if unintended) use of `putTo` to me; the second (reproducing the arbitrary order we chose in `putTo`) less so.

**Comment by rsharo** [comment]
@andi-bigswitch My PrimitiveSink has a selectable endianness.  I could even change endianness between consecutive `putTo()` calls if I really wanted to... but I hope I never need that feature.

But I think I can accept that you should be able to alter your own hashing methodology at will.  I won't harass you any more about changing `MacAddress.putTo()`. :)

All I really need to get is a byte-consistent representation of each `OFValueType` I need to hash.  I need to be sure that I keep the bytes in the same order as the external system so the hashes can be remotely validated.  It probably isn't reasonable to assume loxigen will do that part for me.  One way for me to do that would be to call a common `OFValueType<T>.getBytes()` method as I mentioned before, but the method doesn't exist.

In digging around further, I'm learning more about what you've done with loxigen.  I'm thinking another option would be to make `OFValueType<T>` extend the `Writeable` interface, just as `OFObject` does.

With `getBytes()`, I can grab the bytes and push them into my hasher.  With `Writeable.writeTo()`, I could push the data in more directly (no need to construct a byte array first), even if I have to implement the `ByteBuf` interface to get there.

I don't have a strong preference either way, but I'd like to know if you're interested in a change like this?

**Comment by andi-bigswitch** [comment]
@rsharo - I like the idea to make the OFValueType extend Writeable; as you have inferred, the main reason we didn't end up doing that originally is that `OFPort`s wire representation changed from 2 to 4 bytes after OF1.0. As you mentioned for OFPort, we do think of the 4-byte representation as the canonical representation;  today with OF1.0 being all but extinct for serious use cases, we can definitely say the canonical `writeTo` would write 4 bytes; and loxigen would call an OF1.0 specific method for OF1.0 (like it already does).

I think `writeTo(ByteBuf)` is going to be somewhat more flexible than `getBytes()` which would always have to allocate a new byte array and couldn't easily be composed.

I'd say if there's a pull request that makes those types `Writeable` we'd be happy to include it. I could also look into when I could make that change myself, but no promises that would be super-soon.

**Comment by rsharo** [comment]
@andi-bigswitch Thanks!

Expect a PR shortly for `writeTo(ByteBuf)`.
