### ISSUE TITLE
Invalid pom for OpenflowJ published to Maven

### ISSUE THREAD

**Issue by smartnetworks** [floodlight/loxigen#704]
The OpenflowJ pom file published to repo1.maven.org contains unresolved placeholders. For instance, the version tag reads `<version>3.6.${revision}</version>`, which causes problems for certain mvn and SBT commands. The [Maven docs](https://maven.apache.org/maven-ci-friendly.html) recommends using the plugin [flatten-maven-plugin](https://www.mojohaus.org/flatten-maven-plugin) to generate a valid pom from a CI-friendly one before deploying.

Would it be possible to add this as a part of the Maven release process?

**Comment by andi-bigswitch** [comment]
Happy to consider a PR with this improvement if it works...
